### ISSUE TITLE
Verify migration handles delta migration updates

### ISSUE THREAD

**Issue by bluemodus-mwills** [Kentico/xperience-by-kentico-sitefinity-migration-tool#10]
It is assumed that the Universal Migration Toolkit handles being run multiple times, so that if content is added or updated in the source Sitefinity environment, rerunning the process will bring the new updates into XbyK. However, this requires all Guids provided to the UMT models to be the same every time the process is run.

Validate this is working. If not, reassess.

**Comment by nathaniel-chadwick** [comment]
Closing this out. The migration tool uses Sitefinity's Id's to translate to the Guids of the UMT models. This allows for updates vs. creating new objects every run.
