### ISSUE TITLE
Kentico.Xperience.UMT has package dependency on Kentico.Xperience.Core version >=29.2.0 

### ISSUE THREAD

**Issue by wdixon-bzs** [Kentico/xperience-by-kentico-sitefinity-migration-tool#24]
**Describe the bug**
Upon trying to run the `Migration.Toolkit.Sitefinity.Console` library with `dotnet run` (after following the detailed setup steps and populating `appSettings.json`), I received the following error:

```
The database version '29.3.2' does not match the project version '29.2.0', please check your connection string.
```

It appears that the `Microsoft.Tookit.Sitefinity` class library has a `Kentico.Xperience.UMT` package reference. That package currently has a dependency on the `Kentico.Xperience.Core` package version >=29.2.0. I believe that the `Kentico.Xperience.UMT` package dependency perhaps needs to have its `Kentico.Xperience.Core` dependency version set to >=29.3.2 (or whatever the latest stable release is at the time this fix goes through).

Manually updating the `Kentico.Xperience.Core` package to 29.3.2 fixed this issue for me.

**To Reproduce**
Attempt to run this migration toolkit solution against an Xperience by Kentico project created on version 29.3.2.

**Expected behavior**
Automatic package installation of latest version of `Kentico.Xperience.Core`.

**Screenshots**
![image](https://github.com/user-attachments/assets/d709ad32-eae6-4e67-8d0e-5ef993af6de9)

**Library Version**
1.0.0

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: n/a
 - Version: 10

**Additional context**

**Comment by michalJakubis** [comment]
Hi @wdixon-bzs, Thank you for reporting. We are currently working on updating the Kentico.Xperience.Core in the UMT library. The Sitefinity migration tool will be updated with latest UMT afterwards.

**Comment by michalJakubis** [comment]
Hi @wdixon-bzs, The Sitefinity migration tool has been updated to the latest version of XbK and UMT. [v1.1.0](https://github.com/Kentico/xperience-by-kentico-sitefinity-migration-tool/releases/tag/v1.1.0)
