### ISSUE TITLE
Add ability to migrate some types as Reusable Content Types

### ISSUE THREAD

**Issue by bluemodus-mwills** [Kentico/xperience-by-kentico-sitefinity-migration-tool#9]
With content type migration already established, add the ability to configure a selection of types that will be migrated as reusable content types instead of page content types.

As a result, all content relationship fields that reference reusable content types will be converted to "Content Items" fields instead of "Pages" fields.

**Comment by nathaniel-chadwick** [comment]
Closing this comment as it was required and completed during the completion of issue #5
